[package]
name = "dcmpipe_cli"
version = "0.1.0"
authors = ["neandrake <die.drachen@gmail.com>"]
edition = "2018"

[dependencies]
dcmpipe_lib = { path = "../dcmpipe_lib", version = "0.1" }
byteorder = "1"